### ISSUE TITLE
[Bug]: "net" is not included in package.json dependencies

### ISSUE THREAD

**Issue by iuriguilherme** [afocommunity/ECO-RCON#11]
### What happened?

Module not found: Error: Can't resolve 'net' in 'C:\Users\user\my-project\node_modules\@afocommunity\eco-rcon\lib'

### To Reproduce

```
npm init
npm install @afocommunity/eco-rcon
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bombitmanbomb** [comment]
@iuriguilherme Do note this package does NOT work in the browser and the underlying net package is provided by node. Added explicit bindings to the internal `node:net` package.
